"use client";

import { useState } from "react";

type Equipment = "gate" | "butterfly" | "check" | "prv" | "pump" | "storage" | "controls";
type Scenario = "normal" | "main-break" | "power" | "pump-failure" | "quality";

const equipment: Record<Equipment, { name: string; purpose: string; operation: string; location: string; caution: string }> = {
  gate: { name: "Gate valve", purpose: "Isolates a section of main for repair or maintenance.", operation: "A handwheel raises or lowers a gate. It is normally used fully open or fully closed, not to throttle flow.", location: "Buried on distribution mains, often at intersections and on either side of equipment.", caution: "Operators use current valve maps and established operating procedures before closing valves." },
  butterfly: { name: "Butterfly valve", purpose: "Provides compact isolation, especially on larger pipes.", operation: "A disk rotates a quarter turn. Aligned with the pipe it passes water; across it, the disk blocks water.", location: "Large mains, treatment plants, pump stations, and storage piping.", caution: "Its position and operating torque depend on the valve and the system design." },
  check: { name: "Check valve", purpose: "Stops reverse flow that could damage pumps or reverse a system route.", operation: "Forward flow pushes a hinged disc or spring-loaded poppet open. Reverse pressure closes it automatically.", location: "Immediately downstream of pumps and at selected connections between pressure zones.", caution: "A check valve is not a substitute for a backflow prevention program where one is required." },
  prv: { name: "Pressure-reducing valve (PRV)", purpose: "Keeps downstream pressure within the intended lower-pressure zone.", operation: "A pilot-controlled diaphragm throttles as needed to hold the set downstream pressure.", location: "At pressure-zone boundaries, commonly inside a vault with isolation valves and gauges.", caution: "Settings, bypasses, and maintenance are utility-specific and must follow the approved operating plan." },
  pump: { name: "Pump station", purpose: "Adds energy to move water uphill, into storage, or across the system.", operation: "A motor turns an impeller; discharge isolation and check valves control the route and prevent reverse flow.", location: "At sources, treatment facilities, booster stations, and storage fill lines.", caution: "Many systems use duty/standby pumps, but the installed configuration determines the actual fallback." },
  storage: { name: "Finished-water storage", purpose: "Stores treated water, helps equalize demand, and can provide pressure or emergency reserve.", operation: "A level control fills the tank during lower demand; elevated storage can return water by gravity as the level falls.", location: "Elevated tanks, standpipes, and ground reservoirs connected to distribution zones.", caution: "Available volume and pressure change with elevation, demand, fire flow, and the utility’s operating rules." },
  controls: { name: "Controls & instrumentation", purpose: "Lets operators see and control what the system is doing.", operation: "Pressure transmitters, flow meters, tank-level sensors, chlorine analyzers, alarms, and SCADA communicate system conditions.", location: "Pump stations, tanks, treatment plants, pressure-regulating stations, and critical mains.", caution: "Local indication and manual procedures may be a fallback, but only trained staff should use the approved response plan." },
};

const scenarios: Record<Scenario, { title: string; detail: string; steps: string[] }> = {
  normal: { title: "Normal service", detail: "Treatment, storage, pumps, pressure control, and distribution work together to provide water at customer connections.", steps: ["Treatment sends finished water forward", "Storage balances demand and can add gravity pressure", "Pressure control protects the lower zone", "Sensors give operators a view of the system"] },
  "main-break": { title: "Main break: isolate, then reroute if possible", detail: "Operators use mapped isolation valves to limit the damaged area. A looped main or planned interconnection may feed customers around the break if the system was designed for it.", steps: ["Confirm the break and protect the work area", "Close the smallest practical isolation area", "Use a loop or approved interconnection when available", "Repair, disinfect, test, and return the main under the approved procedure"] },
  power: { title: "Power outage: storage buys time", detail: "Storage can maintain pressure or supply for a limited period. A generator can keep critical pumps and controls running only where it is installed, fueled, tested, and connected for that load.", steps: ["Watch tank level and system pressure", "Start approved standby generation if available", "Prioritize critical service and conserve stored water", "Coordinate restoration using the emergency response plan"] },
  "pump-failure": { title: "Pump failure: change over or use stored water", detail: "A duty/standby arrangement can change to another pump when installed and functional. Storage provides a buffer while operators investigate the failed unit.", steps: ["Alarm identifies loss of flow or pressure", "Start the designated standby pump if available", "Verify check valves and discharge pressure", "Use storage while repair or replacement is coordinated"] },
  quality: { title: "Water-quality concern: protect the system", detail: "The response is not simply to reroute water. Operators follow the utility’s emergency plan to isolate affected facilities or zones, investigate, sample, communicate, and take approved corrective action.", steps: ["Recognize the alarm, report, or sampling result", "Isolate or stop the affected route as directed", "Collect confirmation samples and notify required parties", "Return to service only after the approved clearance process"] },
};

export function EquipmentResilience() {
  const [selected, setSelected] = useState<Equipment>("gate");
  const [scenario, setScenario] = useState<Scenario>("normal");
  const item = equipment[selected];
  const situation = scenarios[scenario];

  return <section className="page equipment-page">
    <p className="eyebrow">PUBLIC WATER SYSTEM EQUIPMENT</p>
    <h2>See the parts that move water—and protect service when something fails.</h2>
    <p className="intro">This is an illustrative distribution system. Actual equipment, valve locations, control logic, and emergency procedures vary by utility.</p>
    <section className="field-photo-study" aria-label="Field photo study: backflow prevention assembly">
      <div className="photo-heading"><div><p className="label">FIELD PHOTO STUDY</p><h3>Read the equipment you see in the field</h3></div><p>Start with the photo, then match each visible part to its job.</p></div>
      <div className="field-photo-grid"><figure className="field-photo"><img src="/equipment-photos/backflow-assembly-field-photo.png" alt="Field photo of a large backflow prevention assembly with two check-valve bodies, shutoff valves, test cocks, and a central relief-valve cover." /><span className="photo-tag tag-inlet">Inlet shutoff</span><span className="photo-tag tag-check-one">Check no. 1</span><span className="photo-tag tag-relief">Relief valve</span><span className="photo-tag tag-check-two">Check no. 2</span><span className="photo-tag tag-outlet">Outlet shutoff</span><span className="photo-tag tag-test">Test cocks</span><figcaption>Labels are approximate from this viewing angle; verify the manufacturer, model, and flow arrow before identifying or operating a field device.</figcaption></figure><div className="field-photo-copy"><h3>Likely a reduced-pressure backflow assembly</h3><p>This assembly appears to have two check valves with a relief valve between them—the standard layout of a reduced-pressure principle (RP) backflow preventer. Its job is to stop contaminated water from moving back toward the drinking-water system.</p><dl><div><dt>Blue handwheels</dt><dd>Upstream and downstream shutoff valves. They isolate the assembly for approved testing or maintenance.</dd></div><div><dt>Large gray bodies</dt><dd>Likely the first and second check-valve sections. Each check opens forward and closes against reverse flow.</dd></div><div><dt>Black center cover</dt><dd>Likely the relief-valve area. If the pressure difference between the checks is lost, this valve can discharge rather than allow a backflow path.</dd></div><div><dt>Small blue-handled fittings</dt><dd>Test cocks. Certified backflow testers connect instruments here to verify the assembly’s performance.</dd></div></dl><p className="equipment-caution"><b>Do not operate it from this lesson.</b> Backflow assemblies are tested and serviced by qualified personnel using the utility’s approved procedure.</p></div></div>
      <p className="photo-sources">Compare with manufacturer references: <a href="https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/reduced-pressure-zone-assemblies/009" target="_blank" rel="noreferrer">reduced-pressure backflow assembly</a>, <a href="https://www.muellercompany.com/water-works/valves/resilient-wedge-gate-valves/" target="_blank" rel="noreferrer">resilient-wedge gate valve</a>, and <a href="https://www.cla-val.com/waterworks/pressure-control-valves/pressure-reducing-valves/90-01-690-01" target="_blank" rel="noreferrer">pressure-reducing valve</a>.</p>
    </section>
    <section className="equipment-explorer" aria-label="Public water equipment explorer">
      <div className="equipment-tabs" role="tablist" aria-label="Choose equipment to inspect">{(Object.keys(equipment) as Equipment[]).map((key) => <button key={key} role="tab" aria-selected={selected === key} className={selected === key ? "selected" : ""} onClick={() => setSelected(key)}>{equipment[key].name}</button>)}</div>
      <div className="equipment-stage"><svg viewBox="0 0 760 290" role="img" aria-label={`${item.name} simplified working view`} className="equipment-diagram"><path className="eq-pipe" d="M55 155H705" /><path className="eq-flow" d="M90 155H255M510 155H675" />
        {selected === "gate" && <g><rect className="eq-body" x="290" y="102" width="180" height="106" rx="8" /><path className="eq-gate" d="M350 63h60v89h-60z" /><path className="eq-stem" d="M380 34v29M345 34h70" /><text className="eq-label" x="322" y="245">gate lifts to open the passage</text></g>}
        {selected === "butterfly" && <g><rect className="eq-body" x="290" y="102" width="180" height="106" rx="8" /><circle className="eq-disk" cx="380" cy="155" r="48" /><path className="eq-shaft" d="M380 79v152" /><text className="eq-label" x="308" y="245">disk turns one quarter turn</text></g>}
        {selected === "check" && <g><rect className="eq-body" x="290" y="102" width="180" height="106" rx="8" /><path className="eq-check" d="M334 111l85 44l-85 43z" /><path className="eq-arrow" d="M510 155h55m-16-16l16 16l-16 16" /><text className="eq-label" x="300" y="245">forward flow opens; reverse flow closes</text></g>}
        {selected === "prv" && <g><rect className="eq-body" x="290" y="102" width="180" height="106" rx="8" /><path className="eq-diaphragm" d="M323 145q57-65 114 0q-57 65-114 0" /><circle className="eq-gauge" cx="555" cy="155" r="33" /><path className="eq-needle" d="M555 155l17-16" /><text className="eq-label" x="295" y="245">valve holds a lower downstream pressure</text></g>}
        {selected === "pump" && <g><circle className="eq-pump" cx="380" cy="155" r="62" /><path className="eq-impeller" d="M380 112v86m-43-43h86m-73-30l60 60m0-60l-60 60" /><path className="eq-arrow" d="M510 155h55m-16-16l16 16l-16 16" /><text className="eq-label" x="304" y="245">motor spins an impeller to add energy</text></g>}
        {selected === "storage" && <g><path className="eq-tank" d="M315 72h130v130H315zM300 72h160M330 202v35m100-35v35" /><path className="eq-water" d="M322 142h116v53H322z" /><path className="eq-pipe-small" d="M380 202v-47" /><text className="eq-label" x="294" y="270">water level changes as the system fills and draws</text></g>}
        {selected === "controls" && <g><rect className="eq-panel" x="305" y="80" width="150" height="145" rx="8" /><path className="eq-screen" d="M325 105h110v58H325z" /><path className="eq-line" d="M337 146l25-20l20 12l35-24" /><circle className="eq-light" cx="340" cy="191" r="8" /><circle className="eq-light" cx="380" cy="191" r="8" /><circle className="eq-light" cx="420" cy="191" r="8" /><path className="eq-signal" d="M455 154h65m-18-18l18 18l-18 18" /><text className="eq-label" x="282" y="260">sensors, alarms, and local controls inform operators</text></g>}
        <text className="eq-label" x="55" y="123">upstream</text><text className="eq-label" x="635" y="123">downstream</text></svg>
        <div className="equipment-copy"><h3>{item.name}</h3><p><b>Job:</b> {item.purpose}</p><p><b>How it works:</b> {item.operation}</p><p><b>Where you see it:</b> {item.location}</p><p className="equipment-caution"><b>Field note:</b> {item.caution}</p></div></div>
    </section>
    <section className="resilience-lab" aria-label="System resilience explorer"><div className="lab-heading"><div><p className="label">SYSTEM VIEW</p><h3>Normal routes and fallback routes</h3></div><p>Choose a system condition to see the equipment operators rely on.</p></div><div className="scenario-controls">{(Object.keys(scenarios) as Scenario[]).map((key) => <button key={key} className={scenario === key ? "selected" : ""} aria-pressed={scenario === key} onClick={() => setScenario(key)}>{scenarios[key].title}</button>)}</div>
      <svg viewBox="0 0 900 370" role="img" aria-label={`${situation.title} public water distribution system diagram`} className="resilience-diagram"><path className="rs-ground" d="M35 290H865" /><path className="rs-main" d="M115 255H760V160H840" /><path className={scenario === "main-break" || scenario === "quality" ? "rs-route muted" : "rs-route"} d="M165 255H720" /><path className={scenario === "main-break" ? "rs-bypass active" : "rs-bypass"} d="M430 255V325H710V255" /><path className={scenario === "power" || scenario === "pump-failure" ? "rs-storage-route active" : "rs-storage-route"} d="M575 105V255" />
        <rect className="rs-treatment" x="70" y="190" width="95" height="65" rx="5" /><text className="rs-text" x="78" y="218">treatment</text><text className="rs-text" x="88" y="237">finished water</text><circle className={scenario === "pump-failure" ? "rs-pump alert" : "rs-pump"} cx="230" cy="255" r="35" /><path className="rs-impeller" d="M230 228v54m-27-27h54m-46-19l38 38m0-38l-38 38" /><text className="rs-text" x="195" y="310">booster pump</text><g className="rs-generator"><rect x="185" y="100" width="95" height="56" rx="5" /><path d="M200 128h22m-11-11v22m28-11h25" /><text className="rs-text" x="180" y="174">generator*</text></g><g><path className="rs-tank" d="M525 55h100v90H525zM512 55h126M542 145v40m66-40v40" /><path className="rs-tank-water" d="M532 102h86v38H532z" /><text className="rs-text" x="528" y="35">storage</text></g><g className={scenario === "main-break" ? "rs-valves isolate" : "rs-valves"}><circle cx="390" cy="255" r="15" /><path d="M379 244l22 22m0-22l-22 22" /><circle cx="690" cy="255" r="15" /><path d="M679 244l22 22m0-22l-22 22" /></g>{scenario === "main-break" && <g className="rs-break"><path d="M525 236l25 38m0-38l-25 38" /><text className="rs-alert" x="490" y="220">main break</text></g>}{scenario === "quality" && <g className="rs-quality"><path d="M525 227l23 40h-46z" /><text className="rs-alert" x="492" y="214">isolate / investigate</text></g>}<rect className="rs-house" x="795" y="112" width="58" height="48" /><path className="rs-house" d="M785 112l39-34l39 34" /><text className="rs-text" x="790" y="190">customers</text><text className="rs-text" x="435" y="350">loop or emergency interconnection*</text></svg>
      <div className="resilience-status"><strong>{situation.title}</strong><p>{situation.detail}</p><ol>{situation.steps.map((step) => <li key={step}>{step}</li>)}</ol><small>*Only where designed, installed, maintained, and authorized by the utility’s emergency plan.</small></div></section>
  </section>;
}
