import { Grade, Question } from "./types";

export type BankQuestion = Question & {
  categoryId: string;
  grade: Grade;
  difficulty: "foundation" | "application" | "calculation";
  reviewStatus: "draft" | "sme-reviewed";
};

type Fact = Omit<BankQuestion, "id" | "prompt" | "reviewStatus"> & { prompt: string };
const situations = ["a routine inspection", "a planned repair", "a customer call", "a morning field round", "an emergency drill", "a maintenance review", "a system walk-through", "a new-operator training session", "a shift handoff", "a troubleshooting visit"];

const facts: Fact[] = [
  { categoryId: "disinfection", grade: "Both", difficulty: "foundation", objectiveId: "main-disinfection", prompt: "Why is a repaired main disinfected before being returned to service?", choices: ["To reduce contamination risk", "To improve map accuracy", "To increase pipe size", "To lower water demand"], answer: 0, explanation: "Work inside a main can introduce contamination. Approved disinfection and testing protect customers before service is restored." },
  { categoryId: "disinfection", grade: "Both", difficulty: "foundation", objectiveId: "chlorine-residual", prompt: "What does a chlorine residual show?", choices: ["Disinfectant remaining in the water", "The age of the pipe", "The depth of a tank", "The number of valves"], answer: 0, explanation: "A residual is disinfectant that remains after demand has been met and can help protect water in the distribution system." },
  { categoryId: "disinfection", grade: "Both", difficulty: "calculation", objectiveId: "disinfectant-dosage", prompt: "If chlorine demand is 1.2 mg/L and the desired residual is 0.8 mg/L, what dose is needed?", choices: ["2.0 mg/L", "0.4 mg/L", "1.2 mg/L", "8.0 mg/L"], answer: 0, explanation: "Dose equals demand plus desired residual: 1.2 + 0.8 = 2.0 mg/L." },
  { categoryId: "disinfection", grade: "Both", difficulty: "foundation", objectiveId: "well-disinfection", prompt: "Why is well volume needed before calculating a disinfectant amount?", choices: ["The dose depends on how much water is in the well", "It changes the pipe material", "It identifies the water source", "It replaces a water test"], answer: 0, explanation: "Chemical amounts depend on the volume being treated, so well volume is a necessary calculation input." },
  { categoryId: "disinfection", grade: "Both", difficulty: "application", objectiveId: "storage-disinfection", prompt: "What is a key reason to inspect and disinfect a storage reservoir?", choices: ["To control contamination risk in stored water", "To increase meter size", "To eliminate all sampling", "To avoid recordkeeping"], answer: 0, explanation: "Storage can affect water quality. Inspection and approved cleaning/disinfection help protect stored water." },
  { categoryId: "disinfection", grade: "D2", difficulty: "foundation", objectiveId: "chloramination", prompt: "What is a D2 operator expected to recognize about chloramination?", choices: ["Its advantages, limits, and chlorine-curve relationship", "That it removes all need for monitoring", "That it is a pipe material", "That it replaces all safety procedures"], answer: 0, explanation: "D2 knowledge includes chloramination compounds, the chlorine curve, and operational advantages and limitations." },
  { categoryId: "disinfection", grade: "D2", difficulty: "application", objectiveId: "dbps", prompt: "What is the D2-level concern with disinfection by-products?", choices: ["Understanding causes and monitoring implications", "Changing hydrant paint", "Reading a pressure gauge only", "Measuring pipe length"], answer: 0, explanation: "D2 operators need knowledge of DBP causes; higher grades add deeper reduction and reporting requirements." },
  { categoryId: "disinfection", grade: "Both", difficulty: "application", objectiveId: "main-disinfection", prompt: "Why may dechlorination be needed after a main-disinfection procedure?", choices: ["To handle disinfectant before water is discharged", "To make pipe bedding stronger", "To calculate pump efficiency", "To identify a service line"], answer: 0, explanation: "Approved dechlorination procedures manage disinfectant before discharge and protect the receiving environment." },
  { categoryId: "disinfection", grade: "Both", difficulty: "foundation", objectiveId: "main-disinfection", prompt: "After disinfection, what confirms a main is ready to return to service?", choices: ["Required testing and approved procedure completion", "A faster valve closure", "A new map symbol", "A larger meter"], answer: 0, explanation: "Return to service follows the applicable approved procedure, including required testing and documentation." },

  { categoryId: "hydraulics", grade: "Both", difficulty: "foundation", objectiveId: "system-layout", prompt: "Which layout has multiple possible routes for water to reach an area?", choices: ["Grid system", "Single service line", "Dead-end only system", "Storage reservoir"], answer: 0, explanation: "A grid provides interconnected routes, which can improve circulation and operational flexibility." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "foundation", objectiveId: "system-basics", prompt: "What is the basic path drinking water follows before it reaches a home?", choices: ["Source or treatment → storage or pumps → distribution mains → service line", "Hydrant → meter → source → treatment", "Service line → reservoir → source", "Valve → chlorine → customer → source"], answer: 0, explanation: "Water is collected or treated, then moved and often stored before distribution mains and a service line bring it to a customer. Individual systems vary, but this is the beginner-friendly system path." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "calculation", objectiveId: "pressure", prompt: "About how many feet of head correspond to 40 psi?", choices: ["92 feet", "17 feet", "40 feet", "400 feet"], answer: 0, explanation: "Multiply psi by 2.31: 40 × 2.31 is about 92 feet of head." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "calculation", objectiveId: "flow-volume", prompt: "A crew collects 500 gallons in 5 minutes. What is the flow rate?", choices: ["100 gpm", "5 gpm", "500 gpm", "2,500 gpm"], answer: 0, explanation: "Flow in gpm equals gallons divided by minutes: 500 ÷ 5 = 100 gpm." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "foundation", objectiveId: "water-hammer", prompt: "What commonly causes water hammer?", choices: ["Stopping moving water too quickly", "Updating a map", "Taking a sample", "Reading a meter"], answer: 0, explanation: "A sudden flow change creates a pressure surge. Gradual valve operation helps reduce it." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "application", objectiveId: "backflow", prompt: "What is a cross-connection?", choices: ["A possible link between drinking water and a contaminant source", "A larger transmission main", "A hydrant cap", "A type of pressure gauge"], answer: 0, explanation: "A cross-connection can permit contamination to enter drinking water under backflow conditions." },
  { categoryId: "hydraulics", grade: "D2", difficulty: "calculation", objectiveId: "velocity-headloss", prompt: "What does water velocity describe?", choices: ["How fast water moves through a pipe", "How much chlorine is in water", "How old a main is", "How many valves exist"], answer: 0, explanation: "Velocity is distance per time, commonly feet per second in a distribution pipe." },
  { categoryId: "hydraulics", grade: "D2", difficulty: "foundation", objectiveId: "velocity-headloss", prompt: "What is a common cause of head loss in a pipe?", choices: ["Friction as water moves through the system", "A clear sample bottle", "A map legend", "A meter register"], answer: 0, explanation: "Friction and system restrictions reduce available energy, creating head loss." },
  { categoryId: "hydraulics", grade: "D2", difficulty: "application", objectiveId: "system-maps", prompt: "Why is a map legend important during an outage?", choices: ["It explains the symbols for valves, mains, and hydrants", "It raises pressure", "It disinfects a main", "It replaces field verification"], answer: 0, explanation: "A legend helps an operator interpret mapped assets before isolating an area." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "calculation", objectiveId: "flow-volume", prompt: "Why is pipe volume useful during a flushing or disinfection task?", choices: ["It estimates water or chemical quantity needed", "It chooses an operator grade", "It changes source water", "It replaces required testing"], answer: 0, explanation: "Volume connects pipe dimensions with the amount of water or disinfectant involved in the task." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "calculation", objectiveId: "flow-volume", prompt: "Scenario: A new line must carry 500 gpm. If the utility's planning target is to keep velocity near 5 feet per second, which candidate pipe is the best starting choice to check?", choices: ["A 6-inch pipe", "A 12-inch pipe", "A 4-inch pipe", "Pipe size does not affect velocity"], answer: 0, explanation: "Use velocity = 0.4085 × gpm ÷ diameter². At 500 gpm, a 6-inch pipe is about 5.7 fps, much closer to the stated target than the other choices. This is a calculation-practice starting point, not a final design: confirm fire flow, pressure, head loss, materials, utility standards, and engineering approval." },
  { categoryId: "hydraulics", grade: "Both", difficulty: "application", objectiveId: "system-layout", prompt: "Scenario: A growing neighborhood is supplied by one dead-end main and has frequent low-residual complaints at the far end. What system improvement should an operator bring forward for engineering review?", choices: ["A looped connection that improves circulation and alternate flow paths", "Closing the only main more often", "Removing all hydrants", "Increasing sample holding time"], answer: 0, explanation: "A looped/grid connection can improve circulation and provide another route for water. It is a planning recommendation for review; the utility and qualified engineer determine the final layout, sizing, cost, and approvals." },
  { categoryId: "hydraulics", grade: "D2", difficulty: "application", objectiveId: "pressure", prompt: "Scenario: A lower pressure zone has excessive pressure because it sits far below the storage tank. Which device is commonly evaluated to control downstream pressure?", choices: ["A pressure-reducing valve (PRV)", "A hydrant cap", "A sample bottle", "A meter register"], answer: 0, explanation: "A PRV is used to reduce and control downstream pressure in applicable pressure-zone arrangements. Verify the zone map, expected flow, pressure settings, bypass needs, and utility design standard before installation or adjustment." },
  { categoryId: "hydraulics", grade: "D2", difficulty: "application", objectiveId: "storage-operations", prompt: "Scenario: A booster pump starts and stops every few minutes as demand changes. Which control strategy is the most appropriate first concept to investigate?", choices: ["Level or pressure controls with suitable set points and anti-short-cycle protection", "Running the pump manually around the clock", "Closing every isolation valve", "Removing all alarms"], answer: 0, explanation: "Frequent starts can indicate a control, storage, pressure-tank, or demand issue. Operators investigate trends and controls; final settings and any equipment changes follow utility procedures and qualified technical review." },

  { categoryId: "operations", grade: "Both", difficulty: "application", objectiveId: "valves", prompt: "Before operating a valve, what should an operator confirm?", choices: ["The correct asset and expected system effect", "That every valve is closed", "That no map is available", "That hydrants are painted"], answer: 0, explanation: "Confirming the correct valve and consequence helps avoid unnecessary shutdowns or pressure problems." },
  { categoryId: "operations", grade: "Both", difficulty: "foundation", objectiveId: "hydrants", prompt: "Why are hydrants flushed?", choices: ["To move water and help assess conditions", "To replace all valves", "To calculate chlorine demand only", "To eliminate system maps"], answer: 0, explanation: "Flushing can renew water and is performed using approved procedures to manage flow, pressure, and safety." },
  { categoryId: "operations", grade: "Both", difficulty: "foundation", objectiveId: "meters", prompt: "What is a key purpose of a water meter?", choices: ["Measuring water use or flow", "Disinfecting a main", "Preventing all backflow", "Supporting a pipe"], answer: 0, explanation: "Meters measure water volume or flow for operational and customer-service purposes." },
  { categoryId: "operations", grade: "Both", difficulty: "application", objectiveId: "pumps", prompt: "Which observation can indicate abnormal pump operation?", choices: ["Unexpected noise or pressure change", "A readable map", "A labeled sample bottle", "A closed toolbox"], answer: 0, explanation: "Changes in sound, vibration, flow, or pressure can indicate a pump condition needing investigation." },
  { categoryId: "operations", grade: "Both", difficulty: "foundation", objectiveId: "generators", prompt: "Why are emergency generators important in a water system?", choices: ["They can support essential operation during a power outage", "They increase pipe diameter", "They replace chlorine", "They eliminate inspections"], answer: 0, explanation: "Backup power can help maintain critical pumping, treatment, monitoring, or communication functions." },
  { categoryId: "operations", grade: "D2", difficulty: "foundation", objectiveId: "chemical-feeders", prompt: "What D2 skill is associated with chemical feeders?", choices: ["Recognizing feeder types, components, and basic troubleshooting", "Changing a map scale", "Determining pipe bedding", "Calculating population only"], answer: 0, explanation: "D2 objectives include chemical feeder types, components, and troubleshooting." },
  { categoryId: "operations", grade: "D2", difficulty: "application", objectiveId: "scada", prompt: "What can SCADA information help an operator do?", choices: ["Monitor and interpret system conditions remotely", "Replace all field checks", "Disinfect water automatically without oversight", "Eliminate emergency plans"], answer: 0, explanation: "SCADA supports monitoring and control; operators still use procedures and verification." },
  { categoryId: "operations", grade: "D2", difficulty: "foundation", objectiveId: "corrosion", prompt: "What is a purpose of cathodic protection?", choices: ["Helping control corrosion on protected equipment", "Increasing chlorine demand", "Measuring water velocity", "Replacing a valve"], answer: 0, explanation: "Cathodic protection is one method used to help manage corrosion in applicable systems." },
  { categoryId: "operations", grade: "Both", difficulty: "application", objectiveId: "valves", prompt: "Why are routine equipment inspections documented?", choices: ["They support maintenance history and follow-up", "They make water heavier", "They remove all leaks", "They change pipe material"], answer: 0, explanation: "Documentation helps track condition, maintenance needs, and operational decisions over time." },
  { categoryId: "operations", grade: "Both", difficulty: "application", objectiveId: "valves", prompt: "Scenario: A crew needs to isolate a block for a repair while keeping the rest of the neighborhood in service. What valve function is needed on the main?", choices: ["An isolation valve that can shut off the affected section", "An air-release valve as the only control", "A customer meter", "A sample tap"], answer: 0, explanation: "Isolation valves divide the system into controllable sections so a repair can be separated from service. Use the current map and field verification, then follow the utility's operating procedure; do not operate a valve until the planned system effect is understood." },
  { categoryId: "operations", grade: "D2", difficulty: "application", objectiveId: "scada", prompt: "Scenario: SCADA shows a reservoir level falling continuously while the fill valve is commanded open. What is the best operator response?", choices: ["Verify the condition in the field and investigate the valve, source flow, instrumentation, and alarm history", "Assume the display is wrong and silence the alarm", "Raise chlorine dose without checking", "Close all zone valves"], answer: 0, explanation: "SCADA is a decision aid, not proof by itself. Compare the trend with field conditions and follow the utility's response procedure before making changes that could affect service or storage." },

  { categoryId: "regulations-safety", grade: "Both", difficulty: "foundation", objectiveId: "operator-certification", prompt: "What is the purpose of operator certification?", choices: ["Supporting qualified operation that protects public health", "Choosing pipe color", "Replacing all training", "Setting water temperature"], answer: 0, explanation: "Certification programs establish qualifications and help support safe, competent drinking-water operation." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "application", objectiveId: "sampling", prompt: "Why must water samples be collected using approved techniques?", choices: ["Poor technique can produce unreliable results", "It raises pressure", "It changes pipe volume", "It replaces public notification"], answer: 0, explanation: "Correct collection, preservation, and timing help ensure that laboratory results represent the water being evaluated." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "foundation", objectiveId: "mcls", prompt: "What is a maximum contaminant level (MCL)?", choices: ["A regulatory limit for a contaminant in drinking water", "A type of pump", "A pipe fitting", "A storage tank shape"], answer: 0, explanation: "An MCL is a drinking-water standard for a specified contaminant." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "application", objectiveId: "public-notification", prompt: "Why might a water system issue public notification?", choices: ["To inform people about certain drinking-water compliance situations", "To choose a pump", "To identify pipe materials", "To calculate velocity"], answer: 0, explanation: "Public notification is required for specified situations so customers receive timely information." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "foundation", objectiveId: "emergency-response", prompt: "What is a core purpose of an emergency response plan?", choices: ["Preparing the system to respond safely to disruptions", "Avoiding all recordkeeping", "Replacing training", "Reducing pipe diameter"], answer: 0, explanation: "Planning helps personnel respond to incidents such as outages, contamination concerns, or natural disasters." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "application", objectiveId: "safety", prompt: "What should happen when an excavation condition appears unsafe?", choices: ["Stop and follow the safety procedure", "Enter quickly", "Remove protective equipment", "Ignore traffic conditions"], answer: 0, explanation: "Unsafe conditions require a pause and the appropriate safety response before work continues." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "foundation", objectiveId: "safety", prompt: "Why is confined-space awareness important?", choices: ["Some spaces can have serious entry hazards", "It increases flow", "It replaces a safety plan", "It changes disinfectant type"], answer: 0, explanation: "Confined spaces may present atmospheric, access, engulfment, or other hazards requiring defined procedures." },
  { categoryId: "regulations-safety", grade: "D2", difficulty: "application", objectiveId: "recordkeeping", prompt: "Why does D2 include recordkeeping knowledge?", choices: ["Operations and compliance depend on accurate records", "Records increase pipe pressure", "Records replace testing", "Records eliminate maintenance"], answer: 0, explanation: "Accurate records support compliance, maintenance, troubleshooting, and communication." },
  { categoryId: "regulations-safety", grade: "Both", difficulty: "foundation", objectiveId: "safety", prompt: "What is the role of personal protective equipment?", choices: ["Reducing exposure to identified hazards", "Increasing flow rate", "Replacing hazard assessment", "Changing water chemistry"], answer: 0, explanation: "PPE is selected for hazards and is part of a broader safety approach, not a substitute for procedures." },

  { categoryId: "mains-piping", grade: "Both", difficulty: "foundation", objectiveId: "pipe-materials", prompt: "Why must pipe and fitting materials be compatible?", choices: ["Compatible materials help create durable, appropriate connections", "They always raise pressure", "They eliminate testing", "They replace bedding"], answer: 0, explanation: "Correct materials and fittings support a sound installation and reduce avoidable failure risk." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "foundation", objectiveId: "main-installation", prompt: "Why is pipe bedding important?", choices: ["It supports the pipe evenly", "It creates chlorine residual", "It replaces a hydrant", "It measures flow"], answer: 0, explanation: "Proper bedding helps support the pipe and reduce stress that can contribute to damage." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "application", objectiveId: "main-installation", prompt: "Why is compaction important during backfill?", choices: ["It helps provide stable support around the pipe", "It increases disinfectant demand", "It changes meter readings", "It replaces inspection"], answer: 0, explanation: "Appropriate backfill and compaction help prevent settlement and pipe movement." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "application", objectiveId: "leaks", prompt: "What can be a sign of a distribution-system leak?", choices: ["Unexpected pressure or water-loss change", "A clear map legend", "A clean sample bottle", "A scheduled meeting"], answer: 0, explanation: "Unusual pressure, flow, surface water, or loss trends can warrant investigation for a leak." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "foundation", objectiveId: "service-connections", prompt: "What is a service connection?", choices: ["The connection bringing water from a main to a property", "A treatment process", "A storage reservoir", "A kind of pump"], answer: 0, explanation: "A service connection links the public distribution main with an individual customer location." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "application", objectiveId: "excavation", prompt: "Why must utility work around an excavation include traffic protection?", choices: ["It helps protect workers and road users", "It raises water pressure", "It disinfects the main", "It measures chlorine"], answer: 0, explanation: "Traffic control is a core part of protecting the work zone and public around utility work." },
  { categoryId: "mains-piping", grade: "D2", difficulty: "foundation", objectiveId: "thrust-restraint", prompt: "Why is thrust restraint used at certain pipe fittings?", choices: ["To resist forces that can move a fitting", "To lower sample holding time", "To change water quality", "To replace valves"], answer: 0, explanation: "Changes in water direction and pressure create forces that require proper restraint in applicable installations." },
  { categoryId: "mains-piping", grade: "D2", difficulty: "application", objectiveId: "thrust-restraint", prompt: "Why is allowable leakage knowledge useful during new-main work?", choices: ["It helps evaluate whether installation performance meets requirements", "It identifies chlorine demand", "It sets public-notification language", "It replaces testing"], answer: 0, explanation: "Leakage testing helps assess the integrity of a newly installed or repaired main under applicable procedures." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "foundation", objectiveId: "pipe-materials", prompt: "Why are joints and fittings important in a distribution main?", choices: ["They connect pipe sections and changes in direction or size", "They measure water quality", "They eliminate pressure", "They replace map symbols"], answer: 0, explanation: "Joints and fittings create the continuous system and accommodate changes in direction, branch, or diameter." },
  { categoryId: "mains-piping", grade: "Both", difficulty: "application", objectiveId: "pipe-materials", prompt: "Scenario: A repair must connect new pipe to an existing main. Before choosing a coupling or fitting, what is the most important first check?", choices: ["The existing pipe material, outside diameter, condition, pressure rating, and approved utility standard", "The color of the nearest hydrant", "The customer's water bill", "Only the length of the street"], answer: 0, explanation: "A fitting must match the actual field conditions and approved materials. Operators identify and verify those conditions; final material selection follows utility specifications and any required engineering direction." },
  { categoryId: "mains-piping", grade: "D2", difficulty: "application", objectiveId: "thrust-restraint", prompt: "Scenario: A pressurized main turns 90 degrees at a new elbow. What installation need should be checked before the main is put in service?", choices: ["Appropriate thrust restraint for the fitting and soil/pressure conditions", "A larger sample bottle", "A lower chlorine residual", "A different map legend"], answer: 0, explanation: "Water pressure pushes on a change in direction. Proper thrust restraint helps keep fittings from moving. The required method is determined from the actual design, pipe, fitting, pressure, soil, and utility standard." },

  { categoryId: "water-quality", grade: "Both", difficulty: "foundation", objectiveId: "coliform", prompt: "Why are bacteriological samples important?", choices: ["They help evaluate possible microbial water-quality concerns", "They measure pipe length", "They replace source protection", "They set pump speed"], answer: 0, explanation: "Bacteriological monitoring is a key part of evaluating drinking-water quality." },
  { categoryId: "water-quality", grade: "Both", difficulty: "foundation", objectiveId: "water-quality-basics", prompt: "What does turbidity describe?", choices: ["Cloudiness caused by particles in water", "The force of water in a pipe", "The age of a hydrant", "The number of service lines"], answer: 0, explanation: "Turbidity is a measure of water cloudiness from suspended particles." },
  { categoryId: "water-quality", grade: "Both", difficulty: "foundation", objectiveId: "water-quality-basics", prompt: "What does pH describe?", choices: ["How acidic or basic water is", "How fast water moves", "How many gallons are in a tank", "How far a main runs"], answer: 0, explanation: "pH expresses acidity or basicity and can affect water quality and corrosion behavior." },
  { categoryId: "water-quality", grade: "Both", difficulty: "foundation", objectiveId: "water-sources", prompt: "Why are wells protected from contamination sources?", choices: ["Groundwater sources can be vulnerable to contaminants", "Protection increases pipe volume", "Protection replaces sampling", "Protection changes flow units"], answer: 0, explanation: "Source protection helps reduce the likelihood that contaminants enter drinking-water supplies." },
  { categoryId: "water-quality", grade: "Both", difficulty: "application", objectiveId: "flushing", prompt: "Why can planned flushing be useful in a distribution system?", choices: ["It can improve circulation and help manage water quality", "It eliminates all sampling", "It changes the source type", "It replaces a maintenance plan"], answer: 0, explanation: "Flushing is an operational tool that can renew water and help address conditions in parts of the distribution system." },
  { categoryId: "water-quality", grade: "Both", difficulty: "foundation", objectiveId: "corrosivity", prompt: "Why does corrosive water matter to a distribution system?", choices: ["It can affect pipes and water quality", "It makes maps inaccurate", "It replaces disinfection", "It reduces all water demand"], answer: 0, explanation: "Corrosivity can affect infrastructure condition and contribute to water-quality issues." },
  { categoryId: "water-quality", grade: "Both", difficulty: "foundation", objectiveId: "water-quality-basics", prompt: "What does hardness generally describe in water?", choices: ["The amount of certain dissolved minerals", "The pressure in a pipe", "The length of a main", "The size of a valve"], answer: 0, explanation: "Hardness is commonly related to dissolved calcium and magnesium minerals." },
  { categoryId: "water-quality", grade: "Both", difficulty: "application", objectiveId: "coliform", prompt: "Why do sample holding times and preservatives matter?", choices: ["They help maintain sample integrity for analysis", "They increase water pressure", "They replace a laboratory", "They change pipe materials"], answer: 0, explanation: "Proper handling helps ensure results reflect the sample condition as accurately as possible." },
  { categoryId: "water-quality", grade: "Both", difficulty: "application", objectiveId: "water-sources", prompt: "What is a sanitary survey concerned with?", choices: ["Conditions that can affect a drinking-water system's safety", "Only customer billing", "Only valve color", "Only pipe diameter"], answer: 0, explanation: "A sanitary survey evaluates system conditions and practices relevant to safe drinking water." }
];

export const questionBank: BankQuestion[] = facts.flatMap((fact, factIndex) => situations.map((situation, situationIndex) => ({ ...fact, id: `bank-${fact.categoryId}-${factIndex + 1}-${situationIndex + 1}`, prompt: `During ${situation}, ${fact.prompt.charAt(0).toLowerCase()}${fact.prompt.slice(1)}`, reviewStatus: "draft" as const })));

export const questionBankByCategory = (categoryId: string) => questionBank.filter((question) => question.categoryId === categoryId);
